# Generated by Django 2.0.4 on 2018-04-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180429_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_user',
            new_name='user',
        ),
    ]
