# Generated by Django 2.0.2 on 2018-02-28 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(default='0', max_length=300)),
                ('lng', models.CharField(default='0', max_length=300)),
                ('note', models.CharField(default='0', max_length=300)),
                ('timeOpen', models.CharField(default='0', max_length=300)),
                ('timeClose', models.CharField(default='0', max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parking Space',
                'verbose_name_plural': 'Parking Spaces',
            },
        ),
    ]
