# Generated by Django 2.0.2 on 2018-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='note',
            field=models.CharField(max_length=300),
        ),
    ]
