# Generated by Django 2.0.3 on 2018-04-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20180228_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='parkingPrice',
            field=models.CharField(default='2', max_length=300),
        ),
    ]
