# Generated by Django 2.0.2 on 2018-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_parkingspace_parkingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='parkingPrice',
            field=models.CharField(max_length=300),
        ),
    ]
