# Generated by Django 2.0.4 on 2018-04-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20180402_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='parkingPrice',
            field=models.IntegerField(default='0'),
        ),
    ]
