# Generated by Django 2.0.2 on 2018-03-07 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0002_auto_20180228_0849'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Past Reservation'), ('C', 'Current Reservation'), ('F', 'Future Reservation')], default='F', max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('processed_time', models.DateTimeField(auto_now_add=True)),
                ('reserved_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_reserved_space', to='listing.ParkingSpace')),
                ('reserved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_reserved_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_time',
            new_name='processed_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservee',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_space',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_space', to='listing.ParkingSpace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
