# Generated by Django 2.0.2 on 2018-04-02 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20180402_2038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_auto_20180307_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_price', models.IntegerField()),
                ('paying_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paying_user', to=settings.AUTH_USER_MODEL)),
                ('space_to_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_to_reserve', to='listing.ParkingSpace')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_price',
            field=models.IntegerField(default=0),
        ),
    ]
